services:
  db:
    image: mysql:8.0.39
    restart: always
    environment:
      MYSQL_DATABASE: 'goldendb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - goldendb:/var/lib/mysql
volumes:
  goldendb:
